### ISSUE TITLE
getting unauthenticated error after install

### ISSUE THREAD

**Issue by farshadff** [B2rana/bagisto-mediamanager#1]
hi , i installed this package and did every thing that documentation said . but when i open it it gives me the unauthenticated error like below :   
![image](https://user-images.githubusercontent.com/17511289/101275499-681bda80-37bb-11eb-8582-db98dc8fc67f.png)
and this is in my console :  
http://localhost:8000/elfinder/connector?_token=o3oQdRCdwyZOcytiX0lHdD341WfY9DGt44ZFv1iy&cmd=open&target=&init=1&tree=1&_=1607243511786

**Comment by B2rana** [comment]
Please make sure elfinder.php must exist under the config folder. Run below command to publish this config file.
```
php artisan vendor:publish --provider='Ridhima\MediaManager\Providers\MediaManagerServiceProvider'
```

Also, create 'public' folder under 'storage/app' before run above command because this folder is missing in Bagisto repo.

**Comment by farshadff** [comment]
well when i try to run that command i get this error :   
```
Unable to locate publishable resources.
Publishing complete.

```
though i added the service provider and cleared cache : 
```
   Webkul\Velocity\Providers\VelocityServiceProvider::class,
        Webkul\BookingProduct\Providers\BookingProductServiceProvider::class,
        Ridhima\MediaManager\Providers\MediaManagerServiceProvider::class
```
and the `elfinder.php` does not exist on config folder

**Comment by B2rana** [comment]
Which method (composer or direct download under packages folder) you are using to install this package?

**Comment by farshadff** [comment]
i required with composer like below :

```
Require this package with Composer
```
should i try the secound method ?

**Comment by B2rana** [comment]
Both will work same. You can try another method meanwhile I will try to debug this on the new setup.

**Comment by farshadff** [comment]
i solved this by coping the `elfinder.php` manually to app/config folder

**Comment by B2rana** [comment]
Glad to know that you have solved the problem.

**Comment by farshadff** [comment]
cool . thanks for the great package <3
