### ISSUE TITLE
Route [admin.mediamanager.popup] not defined. 

### ISSUE THREAD

**Issue by ramlashkar** [B2rana/bagisto-mediamanager#2]
Installed with composer and followed all process as given.

**Comment by B2rana** [comment]
Have you added MediaManagerServiceProvider class file path in app.php file? 
And also, run ```php artisan route:clear``` command

**Comment by B2rana** [comment]
Almost 4 days and didn't receive any feedback from your side. So, I am closing this issue. You can re-open this if you face the same issue again.
