### ISSUE TITLE
Add product image select from media manager

### ISSUE THREAD

**Issue by howdu** [B2rana/bagisto-mediamanager#3]
Do you have any plans for this to work with product add image?

Perhaps adding a new button for select image and open the media manager. I was looking at the vue component perhaps it could be overwritten instead. 
/packages/Webkul/Ui/src/Resources/assets/js/components/image/image-wrapper.vue

**Comment by howdu** [comment]
https://github.com/barryvdh/laravel-elfinder#standalone-popup-selector

**Comment by B2rana** [comment]
Not now because the product has its own folder structure and uses id in the folder name. This can be changeable but will affect the bulk upload extension functionality.
