### ISSUE TITLE
File Manager issue

### ISSUE THREAD

**Issue by ghost** [B2rana/bagisto-mediamanager#4]
![6009437d3b7c7 mceclip1](https://user-images.githubusercontent.com/72428261/105330311-f5907e00-5bf3-11eb-84d1-d010640f5d0b.png)
![6009434891004 mceclip0](https://user-images.githubusercontent.com/72428261/105330316-f6c1ab00-5bf3-11eb-8217-3f53a3898d5c.png)

**Comment by B2rana** [comment]
Hello @zainawanworktech,

Open your config file "config/filesystems.php" and check the key "mediamanager", make sure it contains 'driver' => 'local' or any other driver that Laravel support and run below artisan command.

```
php artisan config:clear
```

**Comment by ghost** [comment]
i am already this code try but they have still error come in my project

**Comment by ghost** [comment]
'dir' => ['files'],

![image](https://user-images.githubusercontent.com/72428261/105446431-ebbe5780-5c93-11eb-9e15-091fecbbde21.png)

**Comment by B2rana** [comment]
Hi @zainawanworktech,

You have added 'mediamanager' disk outside the "disks" setting, which is incorrect. 
Please correct and move this under "disks" key.

**Comment by ghost** [comment]
kindly attached the correct file

**Comment by B2rana** [comment]
Hi @zainawanworktech,

My humble request to you that please read Laravel [documentation](https://laravel.com/docs/7.x/filesystem#introduction) before setup. This issue is related to the wrong configuration.

Please see below screenshot to setup new disk.

![image](https://user-images.githubusercontent.com/1181404/105452162-d7825680-5ca3-11eb-91e9-ddd32b046d3e.png)

**Comment by B2rana** [comment]
Hi @zainawanworktech,

Didn't receive any feedback from your side. So, I am closing this issue. You can re-open this if you face the same issue again.
The solution is already mentioned in the above response.

**Comment by ghost** [comment]
Saturday Sunday is not working day so I can not check feedback

**Comment by ghost** [comment]
ok done they have worked fine

**Comment by B2rana** [comment]
Glad to know that your problem has been solved.
