### ISSUE TITLE
Issue In Media Manager

### ISSUE THREAD

**Issue by Gopesh12** [B2rana/bagisto-mediamanager#5]
Hi,
I am installing the media manager module, but it gives some error after installation "Unauthenticated" , I have followed the
all README file steps , Please check the issue.
Thanks
![Screenshot from 2021-04-14 11-10-37](https://user-images.githubusercontent.com/72005304/114659953-190a2700-9d12-11eb-9b1d-5c9c26f963a8.png)

**Comment by B2rana** [comment]
Please make sure elfinder.php must exist under the config folder. Run the below command to publish this config file.
```
php artisan vendor:publish --provider='Ridhima\MediaManager\Providers\MediaManagerServiceProvider'
```

Or you can manually copy `bagisto-mediamanager/src/Config/elfinder.php` to `app/config` folder.

**Comment by B2rana** [comment]
Almost 6 days and didn't receive any feedback from your side. So, I am closing this issue. You can re-open this if you face the same issue again.
