### ISSUE TITLE
iFrame not loaded in TinyMCE editor because of X-Frame-Options

### ISSUE THREAD

**Issue by Arachnos** [B2rana/bagisto-mediamanager#6]
Hi everyone,
The iframe with mediamanager-popup is not loaded because of CORS policy.

How can I enable the Laravel Frameguard that set X-Frame-Options to SAMEORIGIN ?

**Comment by B2rana** [comment]
Hi Arachnos,

To resolve the issue, please change the value of "X-Frame-Options" from "DENY" to "SAMEORIGIN" in this file [https://github.com/bagisto/bagisto/blob/v1.3.2/packages/Webkul/Core/src/Http/Middleware/SecureHeaders.php](https://github.com/bagisto/bagisto/blob/v1.3.2/packages/Webkul/Core/src/Http/Middleware/SecureHeaders.php)

**Comment by Arachnos** [comment]
Hi B2rana,
I've solved the issue, by cloning and replacing the **SecureHeaders** in **Kernel.php** a new class in my package.

Thanks ;-)
